-- Organ Donation Management System Database Schema

-- Table 1: Donor User Authentication (`register`)
CREATE TABLE IF NOT EXISTS `register` (
  `FIRSTNAME` VARCHAR(100) NOT NULL,
  `LASTNAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(150) PRIMARY KEY,
  `COLOR` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL
);

-- Table 2: Doctor/Admin User Authentication (`register1`)
CREATE TABLE IF NOT EXISTS `register1` (
  `FIRSTNAME` VARCHAR(100) NOT NULL,
  `LASTNAME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(150) PRIMARY KEY,
  `COLOR` VARCHAR(100) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL
);

-- Table 3: Doctor Details (`doctor`)
CREATE TABLE IF NOT EXISTS `doctor` (
  `DOCTORID` VARCHAR(50) PRIMARY KEY,
  `FIRSTNAME` VARCHAR(100) NOT NULL,
  `LASTNAME` VARCHAR(100) NOT NULL,
  `GENDER` VARCHAR(20) NOT NULL,
  `DOB` DATE NOT NULL,
  `EMAIL` VARCHAR(150) NOT NULL,
  `LOCATION` VARCHAR(200) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `SPECIALIZATION` VARCHAR(150) NOT NULL
);

-- Table 4: Donor Details (`donor`)
CREATE TABLE IF NOT EXISTS `donor` (
  `DONORID` VARCHAR(50) PRIMARY KEY,
  `FIRSTNAME` VARCHAR(100) NOT NULL,
  `LASTNAME` VARCHAR(100) NOT NULL,
  `GENDER` VARCHAR(20) NOT NULL,
  `DOB` DATE NOT NULL,
  `BLOODTYPE` VARCHAR(10) NOT NULL,
  `LOCATION` VARCHAR(200) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL
);

-- Table 5: Organ Details (`organ`)
CREATE TABLE IF NOT EXISTS `organ` (
  `ORGANID` VARCHAR(50) PRIMARY KEY,
  `ORGANNAME` VARCHAR(100) NOT NULL,
  `DONORID` VARCHAR(50) NOT NULL,
  `DOCTORID` VARCHAR(50) NOT NULL,
  `DONATEDDATE` DATE NOT NULL
);

-- Table 6: Power of Attorney (`poa`)
CREATE TABLE IF NOT EXISTS `poa` (
  `POAID` VARCHAR(50) PRIMARY KEY,
  `FIRSTNAME` VARCHAR(100) NOT NULL,
  `LASTNAME` VARCHAR(100) NOT NULL,
  `GENDER` VARCHAR(20) NOT NULL,
  `DONORID` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(150) NOT NULL,
  `DOB` DATE NOT NULL,
  `LOCATION` VARCHAR(200) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `RELATION` VARCHAR(100) NOT NULL,
  `DEAD` VARCHAR(10) NOT NULL
);

-- Table 7: Contact Form Submissions (`contact`)
CREATE TABLE IF NOT EXISTS `contact` (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `NAME` VARCHAR(100) NOT NULL,
  `PHONE` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(150) NOT NULL,
  `SUBJECT` VARCHAR(250) NOT NULL,
  `MESSAGE` TEXT NOT NULL,
  `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
